### ISSUE TITLE
Integration not working

### ISSUE THREAD

**Issue by maschbaer** [jmzg93/koboldVR7Integration#5]
Hello,

[home-assistant_2025-03-02T21-10-21.776Z.log](https://github.com/user-attachments/files/19044788/home-assistant_2025-03-02T21-10-21.776Z.log)

I have a VR300.

I installed your integration in HA 2025.2.5 with HACS 2.0.5. 
I entered the OPT code received via email.
Restart HA.

However, no entities show up…

In the logs error show up -> see attached

**Comment by Cirrus94** [comment]
Hello. 

@jmzg93 I am experiencing the same issue. I have a VR7. No Entity is showing up after connecting to the account. See the logs below for details.

[home-assistant_2025-04-30T05-45-33.744Z.log](https://github.com/user-attachments/files/19971875/home-assistant_2025-04-30T05-45-33.744Z.log)

Thanks in advance

**Comment by Cirrus94** [comment]
Hi @jmzg93 

suddenly an entity appeared today. The reason could be that I scanned the floor plan just yesterday.

Nevertheless, there are still some error messages that I have attached in the log.[home-assistant_2025-05-12T13-35-02.337Z.log](https://github.com/user-attachments/files/20162300/home-assistant_2025-05-12T13-35-02.337Z.log)

Thanks in advance.

**Comment by jmzg93** [comment]
Hello again.
The version is now updated. The deprecated Home Assistant versions have been fixed. Features should now appear even if a map hasn't been registered (I just coded it to only show features if there are maps; I didn't realize it).
Please update and test it. I hope it works. Thanks for the feedback.

**Comment by Cirrus94** [comment]
> Hello again. The version is now updated. The deprecated Home Assistant versions have been fixed. Features should now appear even if a map hasn't been registered (I just coded it to only show features if there are maps; I didn't realize it). Please update and test it. I hope it works. Thanks for the feedback.

Hi. Thanks for the quick fix.

I updated the integration today and get still some errors. Not as much as before but still some. Have a look:
[home-assistant_2025-05-13T05-41-51.203Z.log](https://github.com/user-attachments/files/20181828/home-assistant_2025-05-13T05-41-51.203Z.log)

**Comment by jmzg93** [comment]
Hi @Cirrus94 . Wow, that's strange... I can't reproduce that error.
I'll keep investigating to see if I can reproduce it.
If you remove the integration and add it again, do you at least get the robot entity?

**Comment by Cirrus94** [comment]
> Hi [@Cirrus94](https://github.com/Cirrus94) . Wow, that's strange... I can't reproduce that error. I'll keep investigating to see if I can reproduce it. If you remove the integration and add it again, do you at least get the robot entity?

I already have the entity. But the errors in the log above still appear at least after every HA restart.

My System: Raspberry Pi 5
Core 2025.5.1
Supervisor 2025.05.0
Operating System 15.2
Frontend 20250509.0

**Comment by jmzg93** [comment]
Hello @Cirrus94! Since I can't reproduce the errors in my environment, I've uploaded some changes to see if they fix the issues.
Please try version 2.0.2-RC and give me feedback.
Thanks.

**Comment by Cirrus94** [comment]
Hi @jmzg93 

i tried it several times to reinstall the RC version. I also completely removed the integration. But after installation it always shows up as 2.0.1. 

![Image](https://github.com/user-attachments/assets/e17275d6-af29-4de0-97a9-c1d4b82d5ae6)
![Image](https://github.com/user-attachments/assets/db140fee-11e8-4839-b048-c80d84527a16)

**Comment by jmzg93** [comment]
Hello @Cirrus94 !!
Don't worry, it's because I didn't update the manifest in that RC, but in principle, you should have it updated with the RC.
Just in case, I regenerated it so the updated version works correctly.

Are you still seeing errors in the logs?

**Comment by Cirrus94** [comment]
Seems to be a different one now?! 

[Text.txt](https://github.com/user-attachments/files/20207535/Text.txt)

**Comment by Cirrus94** [comment]
And a new one?!

![Image](https://github.com/user-attachments/assets/ac5a43ab-f772-497d-be6b-b0546a0cdb8c)

**Comment by jmzg93** [comment]
Hi @Cirrus94 
As I told you, I don't get these errors, so it's quite difficult to fix something I can't reproduce. Do you have the emptying base that's separate from the robot? I'm trying to find a different cause than mine. If not, contact me privately and we'll see how we can fix your problem, since you'd need to connect to your robot and see what the APIs return (remember, there's no documentation for Kobold's APIs and everything is reverse-engineered).

**Comment by Cirrus94** [comment]
Hi. Yes, I have the emptying base. Don‘t you have it?

**Comment by jmzg93** [comment]
Yes, I have it too... Well, the only thing I can think of is to study your case privately, seeing what the API returns with your robot, which shouldn't be different from mine, but given what I've seen, something must be different.

**Comment by Cirrus94** [comment]
What would you need for further investigation?

**Comment by jmzg93** [comment]
I think it would be best to connect your bot to an email we can both access, and then I'd test it. You could disconnect it from that account at any time and bring it back to yours, and I wouldn't activate the bot without warning, just to see if the integration works. It's the only way I can think of.
